
"""complete_missing_schemas

Revision ID: 77cf85773e30
Revises: v007
Create Date: 2026-03-15 03:25:09.225437

-- ROLLBACK:
-- [Add rollback SQL here]
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '77cf85773e30'
down_revision = 'v007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', sa.String(length=50), nullable=False), schema='accounting')
    op.add_column('accounts', sa.Column('description', sa.Text(), nullable=True), schema='accounting')
    op.drop_constraint(op.f('accounts_code_key'), 'accounts', schema='accounting', type_='unique')
    op.drop_index(op.f('idx_accounts_netsuite_category'), table_name='accounts', schema='accounting')
    op.drop_index(op.f('idx_accounts_parent_id'), table_name='accounts', schema='accounting')
    op.drop_index(op.f('idx_accounts_type'), table_name='accounts', schema='accounting')
    op.create_index(op.f('ix_accounting_accounts_code'), 'accounts', ['code'], unique=True, schema='accounting')
    op.drop_column('accounts', 'is_active', schema='accounting')
    op.drop_column('accounts', 'subtype', schema='accounting')
    op.drop_column('accounts', 'type', schema='accounting')
    op.drop_column('accounts', 'netsuite_category', schema='accounting')
    op.add_column('journal_entries', sa.Column('status', sa.String(length=20), nullable=False), schema='accounting')
    op.add_column('journal_entries', sa.Column('reference', sa.String(length=100), nullable=True), schema='accounting')
    op.add_column('journal_entries', sa.Column('created_by', sa.UUID(), nullable=False), schema='accounting')
    op.alter_column('journal_entries', 'period_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='accounting')
    op.alter_column('journal_entries', 'entry_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               schema='accounting')
    op.alter_column('journal_entries', 'entry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='accounting')
    op.drop_index(op.f('idx_journal_entries_entry_date'), table_name='journal_entries', schema='accounting')
    op.drop_index(op.f('idx_journal_entries_is_posted'), table_name='journal_entries', schema='accounting')
    op.drop_index(op.f('idx_journal_entries_period_id'), table_name='journal_entries', schema='accounting')
    op.create_index(op.f('ix_accounting_journal_entries_period_id'), 'journal_entries', ['period_id'], unique=False, schema='accounting')
    op.create_foreign_key(None, 'journal_entries', 'users', ['created_by'], ['id'], source_schema='accounting', referent_schema='users')
    op.drop_column('journal_entries', 'import_batch_id', schema='accounting')
    op.drop_column('journal_entries', 'is_posted', schema='accounting')
    op.drop_column('journal_entries', 'source', schema='accounting')
    op.add_column('journal_lines', sa.Column('line_order', sa.Integer(), nullable=False), schema='accounting')
    op.drop_index(op.f('idx_journal_lines_account_id'), table_name='journal_lines', schema='accounting')
    op.drop_index(op.f('idx_journal_lines_journal_entry_id'), table_name='journal_lines', schema='accounting')
    op.create_index(op.f('ix_accounting_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False, schema='accounting')
    op.create_index(op.f('ix_accounting_journal_lines_journal_entry_id'), 'journal_lines', ['journal_entry_id'], unique=False, schema='accounting')
    op.drop_constraint(op.f('journal_lines_journal_entry_id_fkey'), 'journal_lines', schema='accounting', type_='foreignkey')
    op.create_foreign_key(None, 'journal_lines', 'journal_entries', ['journal_entry_id'], ['id'], source_schema='accounting', referent_schema='accounting')
    op.drop_column('journal_lines', 'deleted_at', schema='accounting')
    op.drop_column('journal_lines', 'updated_at', schema='accounting')
    op.add_column('periods', sa.Column('fiscal_year', sa.Integer(), nullable=False), schema='accounting')
    op.alter_column('periods', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False,
               schema='accounting')
    op.alter_column('periods', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='accounting')
    op.alter_column('periods', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='accounting')
    op.add_column('customers', sa.Column('tax_id', sa.String(length=20), nullable=False), schema='commerce')
    op.add_column('customers', sa.Column('trade_name', sa.String(length=255), nullable=True), schema='commerce')
    op.add_column('customers', sa.Column('city', sa.String(length=100), nullable=True), schema='commerce')
    op.add_column('customers', sa.Column('country', sa.String(length=3), nullable=False), schema='commerce')
    op.add_column('customers', sa.Column('payment_terms_days', sa.Integer(), nullable=False), schema='commerce')
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=False), schema='commerce')
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='commerce')
    op.alter_column('customers', 'credit_limit',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               schema='commerce')
    op.drop_constraint(op.f('customers_rut_key'), 'customers', schema='commerce', type_='unique')
    op.drop_index(op.f('idx_customers_rut'), table_name='customers', schema='commerce')
    op.create_index(op.f('ix_commerce_customers_tax_id'), 'customers', ['tax_id'], unique=False, schema='commerce')
    op.drop_column('customers', 'payment_days', schema='commerce')
    op.drop_column('customers', 'rut', schema='commerce')
    op.add_column('invoice_items', sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False), schema='commerce')
    op.add_column('invoice_items', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False), schema='commerce')
    op.add_column('invoice_items', sa.Column('line_order', sa.Integer(), nullable=False), schema='commerce')
    op.alter_column('invoice_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='commerce')
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False,
               schema='commerce')
    op.drop_index(op.f('idx_invoice_items_invoice_id'), table_name='invoice_items', schema='commerce')
    op.create_index(op.f('ix_commerce_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False, schema='commerce')
    op.drop_constraint(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', schema='commerce', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['invoice_id'], ['id'], source_schema='commerce', referent_schema='commerce')
    op.create_foreign_key(None, 'invoice_items', 'products', ['product_id'], ['id'], source_schema='commerce', referent_schema='inventory')
    op.drop_column('invoice_items', 'deleted_at', schema='commerce')
    op.drop_column('invoice_items', 'updated_at', schema='commerce')
    op.drop_column('invoice_items', 'discount', schema='commerce')
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=20), nullable=False), schema='commerce')
    op.add_column('invoices', sa.Column('period_id', sa.UUID(), nullable=False), schema='commerce')
    op.add_column('invoices', sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False), schema='commerce')
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), nullable=False), schema='commerce')
    op.add_column('invoices', sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False), schema='commerce')
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True), schema='commerce')
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               schema='commerce')
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               schema='commerce')
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               schema='commerce')
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               schema='commerce')
    op.alter_column('invoices', 'total',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               schema='commerce')
    op.drop_index(op.f('idx_invoices_customer_id'), table_name='invoices', schema='commerce')
    op.drop_index(op.f('idx_invoices_invoice_date'), table_name='invoices', schema='commerce')
    op.drop_index(op.f('idx_invoices_status'), table_name='invoices', schema='commerce')
    op.drop_index(op.f('idx_invoices_vendor_id'), table_name='invoices', schema='commerce')
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', schema='commerce', type_='unique')
    op.create_index(op.f('ix_commerce_invoices_customer_id'), 'invoices', ['customer_id'], unique=False, schema='commerce')
    op.create_index(op.f('ix_commerce_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True, schema='commerce')
    op.create_index(op.f('ix_commerce_invoices_period_id'), 'invoices', ['period_id'], unique=False, schema='commerce')
    op.create_index(op.f('ix_commerce_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False, schema='commerce')
    op.drop_constraint(op.f('invoices_journal_entry_id_fkey'), 'invoices', schema='commerce', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'periods', ['period_id'], ['id'], source_schema='commerce', referent_schema='accounting')
    op.drop_column('invoices', 'journal_entry_id', schema='commerce')
    op.drop_column('invoices', 'type', schema='commerce')
    op.drop_column('invoices', 'invoice_date', schema='commerce')
    op.add_column('vendors', sa.Column('tax_id', sa.String(length=20), nullable=False), schema='commerce')
    op.add_column('vendors', sa.Column('trade_name', sa.String(length=255), nullable=True), schema='commerce')
    op.add_column('vendors', sa.Column('payment_terms_days', sa.Integer(), nullable=False), schema='commerce')
    op.add_column('vendors', sa.Column('is_active', sa.Boolean(), nullable=False), schema='commerce')
    op.alter_column('vendors', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='commerce')
    op.drop_index(op.f('idx_vendors_rut'), table_name='vendors', schema='commerce')
    op.drop_constraint(op.f('vendors_rut_key'), 'vendors', schema='commerce', type_='unique')
    op.create_index(op.f('ix_commerce_vendors_tax_id'), 'vendors', ['tax_id'], unique=False, schema='commerce')
    op.drop_column('vendors', 'credit_limit', schema='commerce')
    op.drop_column('vendors', 'rut', schema='commerce')
    op.drop_column('vendors', 'payment_days', schema='commerce')
    op.add_column('bsc_snapshots', sa.Column('metric_code', sa.String(length=50), nullable=False), schema='financial')
    op.add_column('bsc_snapshots', sa.Column('perspective', sa.String(length=50), nullable=False), schema='financial')
    op.add_column('bsc_snapshots', sa.Column('actual_value', sa.Numeric(precision=18, scale=2), nullable=False), schema='financial')
    op.add_column('bsc_snapshots', sa.Column('target_value', sa.Numeric(precision=18, scale=2), nullable=False), schema='financial')
    op.add_column('bsc_snapshots', sa.Column('status', sa.String(length=20), nullable=False), schema='financial')
    op.add_column('bsc_snapshots', sa.Column('is_active', sa.Boolean(), nullable=False), schema='financial')
    op.alter_column('bsc_snapshots', 'metric_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               schema='financial')
    op.drop_index(op.f('idx_bsc_snapshots_calculated_at'), table_name='bsc_snapshots', schema='financial')
    op.drop_index(op.f('idx_bsc_snapshots_metric_name'), table_name='bsc_snapshots', schema='financial')
    op.drop_index(op.f('idx_bsc_snapshots_period_id'), table_name='bsc_snapshots', schema='financial')
    op.drop_constraint(op.f('uq_bsc_snapshot_period_metric'), 'bsc_snapshots', schema='financial', type_='unique')
    op.create_index(op.f('ix_financial_bsc_snapshots_period_id'), 'bsc_snapshots', ['period_id'], unique=False, schema='financial')
    op.drop_column('bsc_snapshots', 'deleted_at', schema='financial')
    op.drop_column('bsc_snapshots', 'metric_unit', schema='financial')
    op.drop_column('bsc_snapshots', 'calculated_at', schema='financial')
    op.drop_column('bsc_snapshots', 'metric_value', schema='financial')
    op.add_column('products', sa.Column('unit_of_measure', sa.String(length=20), nullable=False), schema='inventory')
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=False), schema='inventory')
    op.add_column('products', sa.Column('min_stock', sa.Numeric(precision=18, scale=4), nullable=False), schema='inventory')
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False), schema='inventory')
    op.add_column('products', sa.Column('is_taxable', sa.Boolean(), nullable=False), schema='inventory')
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               schema='inventory')
    op.alter_column('products', 'sale_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               schema='inventory')
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='inventory')
    op.drop_index(op.f('idx_products_category'), table_name='products', schema='inventory')
    op.drop_index(op.f('idx_products_sku'), table_name='products', schema='inventory')
    op.drop_constraint(op.f('products_sku_key'), 'products', schema='inventory', type_='unique')
    op.create_index(op.f('ix_inventory_products_category'), 'products', ['category'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_products_sku'), 'products', ['sku'], unique=True, schema='inventory')
    op.drop_column('products', 'valuation_method', schema='inventory')
    op.drop_column('products', 'reorder_point', schema='inventory')
    op.drop_column('products', 'unit_cost', schema='inventory')
    op.add_column('stock_movements', sa.Column('stock_before', sa.Numeric(precision=18, scale=4), nullable=False), schema='inventory')
    op.add_column('stock_movements', sa.Column('stock_after', sa.Numeric(precision=18, scale=4), nullable=False), schema='inventory')
    op.add_column('stock_movements', sa.Column('reference', sa.String(length=100), nullable=True), schema='inventory')
    op.add_column('stock_movements', sa.Column('notes', sa.Text(), nullable=True), schema='inventory')
    op.add_column('stock_movements', sa.Column('created_by', sa.UUID(), nullable=False), schema='inventory')
    op.alter_column('stock_movements', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False,
               schema='inventory')
    op.drop_index(op.f('idx_stock_movements_movement_date'), table_name='stock_movements', schema='inventory')
    op.drop_index(op.f('idx_stock_movements_product_id'), table_name='stock_movements', schema='inventory')
    op.create_index(op.f('ix_inventory_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False, schema='inventory')
    op.create_foreign_key(None, 'stock_movements', 'users', ['created_by'], ['id'], source_schema='inventory', referent_schema='users')
    op.drop_column('stock_movements', 'reference_id', schema='inventory')
    op.drop_column('stock_movements', 'deleted_at', schema='inventory')
    op.drop_column('stock_movements', 'movement_date', schema='inventory')
    op.drop_column('stock_movements', 'reference_type', schema='inventory')
    op.drop_column('stock_movements', 'updated_at', schema='inventory')
    op.drop_column('stock_movements', 'unit_cost', schema='inventory')
    op.add_column('ppm_payments', sa.Column('period_id', sa.UUID(), nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('taxable_base', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True), schema='taxes')
    op.add_column('ppm_payments', sa.Column('status', sa.String(length=20), nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('folio', sa.String(length=50), nullable=True), schema='taxes')
    op.alter_column('ppm_payments', 'ppm_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=False,
               schema='taxes')
    op.drop_constraint(op.f('uq_ppm_period'), 'ppm_payments', schema='taxes', type_='unique')
    op.create_index(op.f('ix_taxes_ppm_payments_period_id'), 'ppm_payments', ['period_id'], unique=False, schema='taxes')
    op.create_foreign_key(None, 'ppm_payments', 'periods', ['period_id'], ['id'], source_schema='taxes', referent_schema='accounting')
    op.drop_column('ppm_payments', 'is_suspended', schema='taxes')
    op.drop_column('ppm_payments', 'suspension_reason', schema='taxes')
    op.drop_column('ppm_payments', 'ppm_amount', schema='taxes')
    op.drop_column('ppm_payments', 'gross_income', schema='taxes')
    op.drop_column('ppm_payments', 'period_month', schema='taxes')
    op.drop_column('ppm_payments', 'paid_at', schema='taxes')
    op.drop_column('ppm_payments', 'period_year', schema='taxes')
    op.add_column('tax_config', sa.Column('tax_name', sa.String(length=100), nullable=False), schema='taxes')
    op.add_column('tax_config', sa.Column('tax_code', sa.String(length=20), nullable=False), schema='taxes')
    op.add_column('tax_config', sa.Column('rate', sa.Numeric(precision=7, scale=4), nullable=False), schema='taxes')
    op.add_column('tax_config', sa.Column('applies_to', sa.String(length=50), nullable=False), schema='taxes')
    op.add_column('tax_config', sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False), schema='taxes')
    op.add_column('tax_config', sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True), schema='taxes')
    op.create_unique_constraint(None, 'tax_config', ['tax_code'], schema='taxes')
    op.drop_column('tax_config', 'company_rut', schema='taxes')
    op.drop_column('tax_config', 'company_name', schema='taxes')
    op.drop_column('tax_config', 'deleted_at', schema='taxes')
    op.drop_column('tax_config', 'tax_regime', schema='taxes')
    op.drop_column('tax_config', 'tax_year', schema='taxes')
    op.drop_column('tax_config', 'ppm_rate', schema='taxes')
    op.add_column('tax_results', sa.Column('period_id', sa.UUID(), nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('total_sales', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('total_purchases', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('iva_collected', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('iva_paid', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('iva_balance', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('ppm_paid', sa.Numeric(precision=18, scale=2), nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('is_filed', sa.Boolean(), nullable=False), schema='taxes')
    op.drop_constraint(op.f('tax_results_tax_year_key'), 'tax_results', schema='taxes', type_='unique')
    op.create_index(op.f('ix_taxes_tax_results_period_id'), 'tax_results', ['period_id'], unique=True, schema='taxes')
    op.create_foreign_key(None, 'tax_results', 'periods', ['period_id'], ['id'], source_schema='taxes', referent_schema='accounting')
    op.drop_column('tax_results', 'first_category_tax', schema='taxes')
    op.drop_column('tax_results', 'net_income', schema='taxes')
    op.drop_column('tax_results', 'deleted_at', schema='taxes')
    op.drop_column('tax_results', 'tax_base', schema='taxes')
    op.drop_column('tax_results', 'gross_income', schema='taxes')
    op.drop_column('tax_results', 'tax_year', schema='taxes')
    op.drop_column('tax_results', 'accumulated_loss', schema='taxes')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False,
               schema='users')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"),
               schema='users')
    op.drop_index(op.f('idx_users_deleted_at'), table_name='users', schema='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_users_email'), table_name='users', schema='users')
    op.drop_index(op.f('idx_users_is_active'), table_name='users', schema='users', postgresql_where='(is_active = true)')
    op.drop_constraint(op.f('users_email_key'), 'users', schema='users', type_='unique')
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_users_email'), table_name='users', schema='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], schema='users', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False, schema='users', postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False, schema='users')
    op.create_index(op.f('idx_users_deleted_at'), 'users', ['deleted_at'], unique=False, schema='users', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"),
               schema='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='users')
    op.add_column('tax_results', sa.Column('accumulated_loss', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('tax_year', sa.INTEGER(), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('tax_results', sa.Column('gross_income', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True), schema='taxes')
    op.add_column('tax_results', sa.Column('tax_base', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True), schema='taxes')
    op.add_column('tax_results', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='taxes')
    op.add_column('tax_results', sa.Column('net_income', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True), schema='taxes')
    op.add_column('tax_results', sa.Column('first_category_tax', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True), schema='taxes')
    op.drop_constraint(None, 'tax_results', schema='taxes', type_='foreignkey')
    op.drop_index(op.f('ix_taxes_tax_results_period_id'), table_name='tax_results', schema='taxes')
    op.create_unique_constraint(op.f('tax_results_tax_year_key'), 'tax_results', ['tax_year'], schema='taxes', postgresql_nulls_not_distinct=False)
    op.drop_column('tax_results', 'is_filed', schema='taxes')
    op.drop_column('tax_results', 'calculated_at', schema='taxes')
    op.drop_column('tax_results', 'ppm_paid', schema='taxes')
    op.drop_column('tax_results', 'iva_balance', schema='taxes')
    op.drop_column('tax_results', 'iva_paid', schema='taxes')
    op.drop_column('tax_results', 'iva_collected', schema='taxes')
    op.drop_column('tax_results', 'total_purchases', schema='taxes')
    op.drop_column('tax_results', 'total_sales', schema='taxes')
    op.drop_column('tax_results', 'period_id', schema='taxes')
    op.add_column('tax_config', sa.Column('ppm_rate', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True), schema='taxes')
    op.add_column('tax_config', sa.Column('tax_year', sa.INTEGER(), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('tax_config', sa.Column('tax_regime', sa.VARCHAR(length=20), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('tax_config', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='taxes')
    op.add_column('tax_config', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('tax_config', sa.Column('company_rut', sa.VARCHAR(length=12), autoincrement=False, nullable=False), schema='taxes')
    op.drop_constraint(None, 'tax_config', schema='taxes', type_='unique')
    op.drop_column('tax_config', 'effective_to', schema='taxes')
    op.drop_column('tax_config', 'effective_from', schema='taxes')
    op.drop_column('tax_config', 'applies_to', schema='taxes')
    op.drop_column('tax_config', 'rate', schema='taxes')
    op.drop_column('tax_config', 'tax_code', schema='taxes')
    op.drop_column('tax_config', 'tax_name', schema='taxes')
    op.add_column('ppm_payments', sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='taxes')
    op.add_column('ppm_payments', sa.Column('period_month', sa.INTEGER(), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('gross_income', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('ppm_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False), schema='taxes')
    op.add_column('ppm_payments', sa.Column('suspension_reason', sa.TEXT(), autoincrement=False, nullable=True), schema='taxes')
    op.add_column('ppm_payments', sa.Column('is_suspended', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False), schema='taxes')
    op.drop_constraint(None, 'ppm_payments', schema='taxes', type_='foreignkey')
    op.drop_index(op.f('ix_taxes_ppm_payments_period_id'), table_name='ppm_payments', schema='taxes')
    op.create_unique_constraint(op.f('uq_ppm_period'), 'ppm_payments', ['period_month', 'period_year'], schema='taxes', postgresql_nulls_not_distinct=False)
    op.alter_column('ppm_payments', 'ppm_rate',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=False,
               schema='taxes')
    op.drop_column('ppm_payments', 'folio', schema='taxes')
    op.drop_column('ppm_payments', 'status', schema='taxes')
    op.drop_column('ppm_payments', 'payment_date', schema='taxes')
    op.drop_column('ppm_payments', 'amount_paid', schema='taxes')
    op.drop_column('ppm_payments', 'amount_due', schema='taxes')
    op.drop_column('ppm_payments', 'taxable_base', schema='taxes')
    op.drop_column('ppm_payments', 'period_id', schema='taxes')
    op.add_column('stock_movements', sa.Column('unit_cost', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True), schema='inventory')
    op.add_column('stock_movements', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='inventory')
    op.add_column('stock_movements', sa.Column('reference_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True), schema='inventory')
    op.add_column('stock_movements', sa.Column('movement_date', sa.DATE(), autoincrement=False, nullable=False), schema='inventory')
    op.add_column('stock_movements', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='inventory')
    op.add_column('stock_movements', sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True), schema='inventory')
    op.drop_constraint(None, 'stock_movements', schema='inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_stock_movements_product_id'), table_name='stock_movements', schema='inventory')
    op.create_index(op.f('idx_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False, schema='inventory')
    op.create_index(op.f('idx_stock_movements_movement_date'), 'stock_movements', ['movement_date'], unique=False, schema='inventory')
    op.alter_column('stock_movements', 'quantity',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False,
               schema='inventory')
    op.drop_column('stock_movements', 'created_by', schema='inventory')
    op.drop_column('stock_movements', 'notes', schema='inventory')
    op.drop_column('stock_movements', 'reference', schema='inventory')
    op.drop_column('stock_movements', 'stock_after', schema='inventory')
    op.drop_column('stock_movements', 'stock_before', schema='inventory')
    op.add_column('products', sa.Column('unit_cost', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True), schema='inventory')
    op.add_column('products', sa.Column('reorder_point', sa.NUMERIC(precision=10, scale=3), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='inventory')
    op.add_column('products', sa.Column('valuation_method', sa.VARCHAR(length=10), server_default=sa.text("'PP'::character varying"), autoincrement=False, nullable=False), schema='inventory')
    op.drop_index(op.f('ix_inventory_products_sku'), table_name='products', schema='inventory')
    op.drop_index(op.f('ix_inventory_products_category'), table_name='products', schema='inventory')
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], schema='inventory', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_products_sku'), 'products', ['sku'], unique=False, schema='inventory')
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False, schema='inventory')
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='inventory')
    op.alter_column('products', 'sale_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               schema='inventory')
    op.alter_column('products', 'sku',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='inventory')
    op.drop_column('products', 'is_taxable', schema='inventory')
    op.drop_column('products', 'is_active', schema='inventory')
    op.drop_column('products', 'min_stock', schema='inventory')
    op.drop_column('products', 'cost_price', schema='inventory')
    op.drop_column('products', 'unit_of_measure', schema='inventory')
    op.add_column('bsc_snapshots', sa.Column('metric_value', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True), schema='financial')
    op.add_column('bsc_snapshots', sa.Column('calculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='financial')
    op.add_column('bsc_snapshots', sa.Column('metric_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='financial')
    op.add_column('bsc_snapshots', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='financial')
    op.drop_index(op.f('ix_financial_bsc_snapshots_period_id'), table_name='bsc_snapshots', schema='financial')
    op.create_unique_constraint(op.f('uq_bsc_snapshot_period_metric'), 'bsc_snapshots', ['period_id', 'metric_name'], schema='financial', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_bsc_snapshots_period_id'), 'bsc_snapshots', ['period_id'], unique=False, schema='financial')
    op.create_index(op.f('idx_bsc_snapshots_metric_name'), 'bsc_snapshots', ['metric_name'], unique=False, schema='financial')
    op.create_index(op.f('idx_bsc_snapshots_calculated_at'), 'bsc_snapshots', [sa.literal_column('calculated_at DESC')], unique=False, schema='financial')
    op.alter_column('bsc_snapshots', 'metric_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               schema='financial')
    op.drop_column('bsc_snapshots', 'is_active', schema='financial')
    op.drop_column('bsc_snapshots', 'status', schema='financial')
    op.drop_column('bsc_snapshots', 'target_value', schema='financial')
    op.drop_column('bsc_snapshots', 'actual_value', schema='financial')
    op.drop_column('bsc_snapshots', 'perspective', schema='financial')
    op.drop_column('bsc_snapshots', 'metric_code', schema='financial')
    op.add_column('vendors', sa.Column('payment_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False), schema='commerce')
    op.add_column('vendors', sa.Column('rut', sa.VARCHAR(length=12), autoincrement=False, nullable=True), schema='commerce')
    op.add_column('vendors', sa.Column('credit_limit', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True), schema='commerce')
    op.drop_index(op.f('ix_commerce_vendors_tax_id'), table_name='vendors', schema='commerce')
    op.create_unique_constraint(op.f('vendors_rut_key'), 'vendors', ['rut'], schema='commerce', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_vendors_rut'), 'vendors', ['rut'], unique=False, schema='commerce')
    op.alter_column('vendors', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True,
               schema='commerce')
    op.drop_column('vendors', 'is_active', schema='commerce')
    op.drop_column('vendors', 'payment_terms_days', schema='commerce')
    op.drop_column('vendors', 'trade_name', schema='commerce')
    op.drop_column('vendors', 'tax_id', schema='commerce')
    op.add_column('invoices', sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False), schema='commerce')
    op.add_column('invoices', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False), schema='commerce')
    op.add_column('invoices', sa.Column('journal_entry_id', sa.UUID(), autoincrement=False, nullable=True), schema='commerce')
    op.drop_constraint(None, 'invoices', schema='commerce', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_journal_entry_id_fkey'), 'invoices', 'journal_entries', ['journal_entry_id'], ['id'], source_schema='commerce', referent_schema='accounting')
    op.drop_index(op.f('ix_commerce_invoices_vendor_id'), table_name='invoices', schema='commerce')
    op.drop_index(op.f('ix_commerce_invoices_period_id'), table_name='invoices', schema='commerce')
    op.drop_index(op.f('ix_commerce_invoices_invoice_number'), table_name='invoices', schema='commerce')
    op.drop_index(op.f('ix_commerce_invoices_customer_id'), table_name='invoices', schema='commerce')
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], schema='commerce', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False, schema='commerce')
    op.create_index(op.f('idx_invoices_status'), 'invoices', ['status'], unique=False, schema='commerce')
    op.create_index(op.f('idx_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False, schema='commerce')
    op.create_index(op.f('idx_invoices_customer_id'), 'invoices', ['customer_id'], unique=False, schema='commerce')
    op.alter_column('invoices', 'total',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               schema='commerce')
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               schema='commerce')
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               schema='commerce')
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True,
               schema='commerce')
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               schema='commerce')
    op.drop_column('invoices', 'notes', schema='commerce')
    op.drop_column('invoices', 'paid_amount', schema='commerce')
    op.drop_column('invoices', 'currency', schema='commerce')
    op.drop_column('invoices', 'issue_date', schema='commerce')
    op.drop_column('invoices', 'period_id', schema='commerce')
    op.drop_column('invoices', 'invoice_type', schema='commerce')
    op.add_column('invoice_items', sa.Column('discount', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='commerce')
    op.add_column('invoice_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='commerce')
    op.add_column('invoice_items', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='commerce')
    op.drop_constraint(None, 'invoice_items', schema='commerce', type_='foreignkey')
    op.drop_constraint(None, 'invoice_items', schema='commerce', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', 'invoices', ['invoice_id'], ['id'], source_schema='commerce', referent_schema='commerce', ondelete='CASCADE')
    op.drop_index(op.f('ix_commerce_invoice_items_invoice_id'), table_name='invoice_items', schema='commerce')
    op.create_index(op.f('idx_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False, schema='commerce')
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False,
               schema='commerce')
    op.alter_column('invoice_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='commerce')
    op.drop_column('invoice_items', 'line_order', schema='commerce')
    op.drop_column('invoice_items', 'tax_rate', schema='commerce')
    op.drop_column('invoice_items', 'discount_pct', schema='commerce')
    op.add_column('customers', sa.Column('rut', sa.VARCHAR(length=12), autoincrement=False, nullable=True), schema='commerce')
    op.add_column('customers', sa.Column('payment_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False), schema='commerce')
    op.drop_index(op.f('ix_commerce_customers_tax_id'), table_name='customers', schema='commerce')
    op.create_index(op.f('idx_customers_rut'), 'customers', ['rut'], unique=False, schema='commerce')
    op.create_unique_constraint(op.f('customers_rut_key'), 'customers', ['rut'], schema='commerce', postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'credit_limit',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               schema='commerce')
    op.alter_column('customers', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True,
               schema='commerce')
    op.drop_column('customers', 'is_active', schema='commerce')
    op.drop_column('customers', 'payment_terms_days', schema='commerce')
    op.drop_column('customers', 'country', schema='commerce')
    op.drop_column('customers', 'city', schema='commerce')
    op.drop_column('customers', 'trade_name', schema='commerce')
    op.drop_column('customers', 'tax_id', schema='commerce')
    op.alter_column('periods', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               schema='accounting')
    op.alter_column('periods', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               schema='accounting')
    op.alter_column('periods', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               schema='accounting')
    op.drop_column('periods', 'fiscal_year', schema='accounting')
    op.add_column('journal_lines', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='accounting')
    op.add_column('journal_lines', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='accounting')
    op.drop_constraint(None, 'journal_lines', schema='accounting', type_='foreignkey')
    op.create_foreign_key(op.f('journal_lines_journal_entry_id_fkey'), 'journal_lines', 'journal_entries', ['journal_entry_id'], ['id'], source_schema='accounting', referent_schema='accounting', ondelete='CASCADE')
    op.drop_index(op.f('ix_accounting_journal_lines_journal_entry_id'), table_name='journal_lines', schema='accounting')
    op.drop_index(op.f('ix_accounting_journal_lines_account_id'), table_name='journal_lines', schema='accounting')
    op.create_index(op.f('idx_journal_lines_journal_entry_id'), 'journal_lines', ['journal_entry_id'], unique=False, schema='accounting')
    op.create_index(op.f('idx_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False, schema='accounting')
    op.drop_column('journal_lines', 'line_order', schema='accounting')
    op.add_column('journal_entries', sa.Column('source', sa.VARCHAR(length=30), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False), schema='accounting')
    op.add_column('journal_entries', sa.Column('is_posted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False), schema='accounting')
    op.add_column('journal_entries', sa.Column('import_batch_id', sa.UUID(), autoincrement=False, nullable=True), schema='accounting')
    op.drop_constraint(None, 'journal_entries', schema='accounting', type_='foreignkey')
    op.drop_index(op.f('ix_accounting_journal_entries_period_id'), table_name='journal_entries', schema='accounting')
    op.create_index(op.f('idx_journal_entries_period_id'), 'journal_entries', ['period_id'], unique=False, schema='accounting')
    op.create_index(op.f('idx_journal_entries_is_posted'), 'journal_entries', ['is_posted'], unique=False, schema='accounting')
    op.create_index(op.f('idx_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False, schema='accounting')
    op.alter_column('journal_entries', 'entry_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               schema='accounting')
    op.alter_column('journal_entries', 'entry_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               schema='accounting')
    op.alter_column('journal_entries', 'period_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='accounting')
    op.drop_column('journal_entries', 'created_by', schema='accounting')
    op.drop_column('journal_entries', 'reference', schema='accounting')
    op.drop_column('journal_entries', 'status', schema='accounting')
    op.add_column('accounts', sa.Column('netsuite_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='accounting')
    op.add_column('accounts', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False), schema='accounting')
    op.add_column('accounts', sa.Column('subtype', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='accounting')
    op.add_column('accounts', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False), schema='accounting')
    op.drop_index(op.f('ix_accounting_accounts_code'), table_name='accounts', schema='accounting')
    op.create_index(op.f('idx_accounts_type'), 'accounts', ['type'], unique=False, schema='accounting')
    op.create_index(op.f('idx_accounts_parent_id'), 'accounts', ['parent_id'], unique=False, schema='accounting')
    op.create_index(op.f('idx_accounts_netsuite_category'), 'accounts', ['netsuite_category'], unique=False, schema='accounting')
    op.create_unique_constraint(op.f('accounts_code_key'), 'accounts', ['code'], schema='accounting', postgresql_nulls_not_distinct=False)
    op.drop_column('accounts', 'description', schema='accounting')
    op.drop_column('accounts', 'account_type', schema='accounting')
    # ### end Alembic commands ###
